
server:
  port: 80
  servlet:
  context-path: /blade
  undertow:
    io-threads: 4
    worker-threads: 20
    buffer-size: 1024
    direct-buffers: true
spring:
  cache:
    ehcache:
      config: classpath:config/ehcache.xml
  http:
    encoding:
      charset: UTF-8
      force: true
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 1024MB
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      log-condition-evaluation-delta: false
logging:
  config: classpath:log/logback_${blade.env}.xml

# mybatis
mybatis-plus:
  mapper-locations: classpath:org/springblade/**/mapper/*Mapper.xml
  typeAliasesPackage: org.springblade.**.entity
  global-config:
    refresh: ${blade.dev-mode}
    banner: false
    db-config:
      id-type: 0
      field-strategy: 2
      column-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
swagger:
  title: SpringBlade 接口文档系统
  description: SpringBlade 接口文档系统
  version: 2.0.0
  license: Powered By SpringBlade
  licenseUrl: https://bladex.vip
  terms-of-service-url: https://bladex.vip
  contact:
    name: smallchill
    email: smallchill@163.com
    url: https://gitee.com/smallc
blade:
  secure:
    url:
      exclude-patterns:
        - /blade-test/**
    client:
      - client-id: sword
        path-patterns:
          - /blade-sword/**
      - client-id: saber
        path-patterns:
          - /blade-saber/**
  tenant:
    column: tenant_code
    tables:
      - blade_notice
